version: "3.8"
services:
  db:
    image: postgres:latest
    container_name: nextjs-app
    restart: always
    ports:
      - "5431:5432"
    environment:
      POSTGRES_DB: nextjs-app-db
      POSTGRES_USER: daehwan
      POSTGRES_PASSWORD: password
    volumes:
      - ./data:/var/lib/postgresql/data